Docker 2
Otus-DevOps-2021-08/bergentroll_microservices pull request #1
Opened 2021-11-23 20:58 UTC by bergentroll

Выполнены задания `docker`, `docker-2`, включая задания со звёздочками.

Такими командами можно развернуть монолит у себя на облаке:

```bash
pushd docker-monolith/infra/packer/
# You may create variables file from variables.json.example
packer build -var-file=variables.json docker.json
popd 

pushd docker-monolith/infra/terraform/
# Terraform requires variables, see terraform.tfvars.example
terraform apply
popd 

pushd docker-monolith/infra/ansible/
# Inventory populates with terrafrom apply
ansible-playbook monolith.yml --tags app
popd
```

2021-11-24 07:19 UTC, mrgreyves requested changes
Здравствуйте!)
В этот репозиторий нужно так же добавить тесты, там не сложно =)

2021-11-24 09:56 UTC, bergentroll commented
@mrgreyves
Владимир, а где это описано? В тексте ДЗ не нашёл. Там тот же пайплайн для GA, что и в `{{ username }}_infra`?

2021-11-24 11:20 UTC, bergentroll commented
@mrgreyves 
Прошляпил, исправился.

2021-11-25 07:20 UTC, mrgreyves approved these changes
Здравствуйте!)
Да ничего страшного, вот теперь все чотенько =)

2021-11-26 08:30 UTC, merged